#!/bin/bash
# Demo Recording Script for AXIOM Voice Agent
# This script creates a GIF showing the complete workflow

echo "🎬 AXIOM Demo Recording Script"
echo "================================"
echo ""
echo "This will create a demo showing:"
echo "1. Idle state with breathing animation"
echo "2. Thinking state (processing)"
echo "3. Speaking state with waveform"
echo "4. Carousel navigation to robot dog"
echo "5. 3D hologram activation"
echo ""

# Check if ffmpeg is installed
if ! command -v ffmpeg &> /dev/null; then
    echo "❌ ffmpeg not found. Installing..."
    sudo apt-get update && sudo apt-get install -y ffmpeg
fi

# Create output directory
mkdir -p assets/demo

echo "✅ Ready to record"
echo ""
echo "📋 Manual Steps:"
echo "1. Open http://localhost:8000 in browser"
echo "2. Click 'Initialize System'"
echo "3. Open browser console (F12)"
echo "4. Run the demo sequence:"
echo ""
echo "   // Copy and paste this into browser console:"
echo "   (async () => {"
echo "     console.log('🎬 Starting AXIOM Demo...');"
echo "     "
echo "     // Wait for initialization"
echo "     await new Promise(r => setTimeout(r, 2000));"
echo "     "
echo "     // 1. Show idle state (3 seconds)"
echo "     console.log('1️⃣ Idle state');"
echo "     updateVoiceState('idle');"
echo "     await new Promise(r => setTimeout(r, 3000));"
echo "     "
echo "     // 2. Navigate to robot dog"
echo "     console.log('2️⃣ Navigating to Unitree Go2');"
echo "     goToSlide(0);"
echo "     await new Promise(r => setTimeout(r, 1000));"
echo "     "
echo "     // 3. Flash card (keyword trigger)"
echo "     console.log('3️⃣ Keyword detected: robot dog');"
echo "     const card = document.querySelector('[data-index=\"0\"]');"
echo "     card.classList.add('triggered');"
echo "     setTimeout(() => card.classList.remove('triggered'), 1000);"
echo "     await new Promise(r => setTimeout(r, 500));"
echo "     "
echo "     // 4. Enter thinking state"
echo "     console.log('4️⃣ Thinking...');"
echo "     updateVoiceState('thinking');"
echo "     await new Promise(r => setTimeout(r, 2000));"
echo "     "
echo "     // 5. Activate 3D hologram"
echo "     console.log('5️⃣ Activating hologram');"
echo "     activateHologram('unitree');"
echo "     await new Promise(r => setTimeout(r, 3000));"
echo "     "
echo "     // 6. Enter speaking state"
echo "     console.log('6️⃣ Speaking...');"
echo "     updateVoiceState('speaking');"
echo "     await new Promise(r => setTimeout(r, 5000));"
echo "     "
echo "     // 7. Return to idle"
echo "     console.log('7️⃣ Returning to idle');"
echo "     updateVoiceState('idle');"
echo "     await new Promise(r => setTimeout(r, 2000));"
echo "     "
echo "     // 8. Close hologram"
echo "     console.log('8️⃣ Closing hologram');"
echo "     deactivateHologram();"
echo "     "
echo "     console.log('✅ Demo complete!');"
echo "   })();"
echo ""
echo "5. Use OBS Studio or SimpleScreenRecorder to record the browser window"
echo "6. Convert to GIF using:"
echo "   ffmpeg -i recording.mp4 -vf 'fps=15,scale=1280:-1:flags=lanczos' -c:v gif assets/demo/axiom_demo.gif"
echo ""
echo "📌 Alternative: Use browser's built-in recording or the browser subagent"
